name: push image to acr

on:
  push:
    branches:
      - main
env:
  ALIYUN_ACR_USER: ${{ secrets.ALIYUN_ACR_USER }}
  ALIYUN_ACR_PASSWORD: ${{ secrets.ALIYUN_ACR_PASSWORD }}
jobs:
  push_image_to_acr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          submodules: true 

      - name: Login to Aliyun ACR
        run: |
          echo ${{secrets.ALIYUN_ACR_PASSWORD}} | docker login --username ${{secrets.ALIYUN_ACR_USER}} --password-stdin registry.cn-hangzhou.aliyuncs.com
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
      - name: Run shell scripts
        run: |
          bash push-images.sh

      - name: Commit and Push changes
        run: |
          git add push.log
          git commit -m "GitHub Actions Auto Builder"
          git push  --force --quiet  origin main