name: push image to acr

on:
  push:
    branches:
      - main
env:
  ALIYUN_ACR_USER: ${{ secrets.ALIYUN_ACR_USER }}
  ALIYUN_ACR_PASSWORD: ${{ secrets.ALIYUN_ACR_PASSWORD }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GIT_REPO: "github.com/git1e/dockerimages-to-acr.git"
jobs:
  push_image_to_acr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          submodules: true 

      - name: Login to Aliyun ACR
        run: |
          echo ${{secrets.ALIYUN_ACR_PASSWORD}} | docker login --username ${{secrets.ALIYUN_ACR_USER}} --password-stdin registry.cn-hangzhou.aliyuncs.com
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
      - name: Run shell scripts
        run: |
          bash push-images.sh

      - name: Commit and Push changes
        run: |
          # git config user.name "${{secrets.GIT_NAME}}"
          # git config user.email "${{secrets.GIT_EMAIL}}"
          git add push.log
          git commit -m "GitHub Actions Auto Builder"
          # git remote add gh_origin  "https://x-access-token:${GH_TOKEN}@${GIT_REPO}"
          # git push  --force --quiet  gh_origin main
          git push  --force --quiet  origin main